# Generated by Django 5.0.2 on 2025-12-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventosAcademicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(max_length=100)),
                ('fecha_realizacion', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('publico_objetivo', models.CharField(max_length=100)),
                ('programa_educativo', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('cupo_maximo', models.IntegerField(blank=True, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
