# Generated by Django 5.0.2 on 2025-12-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0004_eventosacademicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosacademicos',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
